name: ss-nt-mpe-rc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools<70.0.0
  - wheel
  - numpy=1.26.3
  - numba=0.60.0
  - scipy=1.14.0
  - pandas=2.2.2
  - librosa=0.10.2.post1
  - pip:
      - -r requirement.txt